# Generated by Django 5.1.15 on 2026-09-22 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('ajuste', 'Ajuste'), ('venta', 'Venta'), ('cancelacion', 'Cancelación'), ('devolucion', 'Devolución')], max_length=20, verbose_name='tipo de movimiento')),
                ('quantity', models.IntegerField(help_text='Positivo para entradas/devoluciones, negativo para ventas/salidas.', verbose_name='cantidad')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('stock_after', models.PositiveIntegerField(help_text='Stock de la variante inmediatamente después de este movimiento.', verbose_name='stock resultante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
