# Generated by Django 5.1.15 on 2026-09-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='categoría padre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio base')),
                ('is_active', models.BooleanField(default=True, help_text='Un producto inactivo no aparece en el catálogo ni puede comprarse.', verbose_name='activo')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='umbral de bajo stock (M21)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='texto alternativo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='imagen principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('attribute_name', models.CharField(blank=True, default='Presentación', help_text='Ej. Talla, Color, Presentación.', max_length=50, verbose_name='atributo')),
                ('attribute_value', models.CharField(blank=True, default='Único', help_text='Ej. M, Rojo, 30ml, Único (si el producto no tiene variantes reales).', max_length=50, verbose_name='valor del atributo')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, usa el precio base del producto.', max_digits=10, null=True, verbose_name='precio propio (opcional)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='stock disponible')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'variante de producto',
                'verbose_name_plural': 'variantes de producto',
                'ordering': ['attribute_name', 'attribute_value'],
                'constraints': [models.UniqueConstraint(fields=('product', 'attribute_name', 'attribute_value'), name='unique_variant_per_attribute_value')],
            },
        ),
    ]
