# Generated by Django 5.1.15 on 2026-09-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional: úsala cuando la variante se vea distinto (p. ej. un color). Si se deja vacía, la vista de producto usa la imagen general del producto.', null=True, upload_to='variants/%Y/%m/', verbose_name='imagen de la variante'),
        ),
    ]
