# Generated by Django 5.1.15 on 2026-09-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description_override',
            field=models.TextField(blank=True, help_text='Opcional: úsala cuando esta variante necesite su propio texto (p. ej. rendimiento distinto según la presentación). Si se deja vacía, la vista de producto usa la descripción general del producto.', verbose_name='descripción propia (opcional)'),
        ),
    ]
